import type { TourTemplate } from "./types";

export const SEED_TOURS: TourTemplate[] = [
  {
    id: "#T0001A",
    reference: "#T0001A",
    tripName: "Autumn Foliage & Deer Paths",
    officeLocation: "Osaka",
    durationTier: "Half Day 5hrs",
    status: "active",
    price: 60000,
    startTime: "09:00",
    viewedCount: 27,
    bookedCount: 3,
    userName: null,
    userEmail: null,
    userSource: null,
    paymentStatus: null,
    serviceType: "Sightseeing Charter",
    airport: null,
    passengers: null,
    luggage: null,
    waypoints: {
      pickup: "Osaka Station",
      pickupTime: "09:00",
      stopovers: [
        { location: "Nara Park", waitTime: "90 min" },
        { location: "Todai-ji Temple", waitTime: "60 min" },
      ],
      dropoff: "Osaka Station",
    },
    tripDistanceKm: 80.2,
    tripDurationMins: 330,
    previewLinks: {
      tourDetails:
        "https://www.zengoride.com/tours/autumn-foliage-deer-paths",
      tourBooking: "/tours/autumn-foliage-deer-paths/00001/2026-09-02",
    },
    driverName: null,
    plateNumber: null,
    useDefaultPrice: true,
    vehiclePricing: null,
  },
  {
    id: "#T0002A",
    reference: "#T0002A",
    tripName: "Buddha by the Beach",
    officeLocation: "Tokyo",
    durationTier: "Half Day 5hrs",
    status: "active",
    price: 50000,
    startTime: "09:00",
    viewedCount: 41,
    bookedCount: 7,
    userName: null,
    userEmail: null,
    userSource: null,
    paymentStatus: null,
    serviceType: "Sightseeing Charter",
    airport: null,
    passengers: null,
    luggage: null,
    waypoints: {
      pickup: "Kamakura Station",
      pickupTime: "09:00",
      stopovers: [
        { location: "Great Buddha (Daibutsu)", waitTime: "45 min" },
        { location: "Yuigahama Beach", waitTime: "30 min" },
      ],
      dropoff: "Kamakura Station",
    },
    tripDistanceKm: 45.0,
    tripDurationMins: 300,
    previewLinks: {
      tourDetails: "https://www.zengoride.com/tours/buddha-by-the-beach",
      tourBooking: "/tours/buddha-by-the-beach/00002/2026-09-02",
    },
    driverName: null,
    plateNumber: null,
    useDefaultPrice: true,
    vehiclePricing: null,
  },
  {
    id: "#T0003A",
    reference: "#T0003A",
    tripName: "Flavors of Edo",
    officeLocation: "Tokyo",
    durationTier: "Full Day 10hrs",
    status: "inactive",
    price: 80000,
    startTime: "10:00",
    viewedCount: 12,
    bookedCount: 1,
    userName: null,
    userEmail: null,
    userSource: null,
    paymentStatus: null,
    serviceType: "Sightseeing Charter",
    airport: null,
    passengers: null,
    luggage: null,
    waypoints: {
      pickup: "Tokyo Station",
      pickupTime: "10:00",
      stopovers: [
        { location: "Tsukiji Outer Market", waitTime: "60 min" },
        { location: "Asakusa Senso-ji", waitTime: "45 min" },
      ],
      dropoff: "Shibuya Crossing",
    },
    tripDistanceKm: 30.5,
    tripDurationMins: 600,
    previewLinks: {
      tourDetails: "https://www.zengoride.com/tours/flavors-of-edo",
      tourBooking: "/tours/flavors-of-edo/00003/2026-09-02",
    },
    driverName: null,
    plateNumber: null,
    useDefaultPrice: true,
    vehiclePricing: null,
  },
];
